on:
  pull_request: ~
  push:
    branches-ignore:
      - master
      - gh-pages
name: Check build (non-master)
jobs:
  check-build:
    runs-on: ubuntu-latest
    name: Check build
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Check build and create artifact
        uses: ./.github/actions/check-build